Use new base images
arcalot/arcaflow-plugin-template-python pull request #39
Opened 2023-07-04 10:02 UTC by dustinblack

## Changes introduced with this PR

In order to better control drift that can lead to CI build failures, the Dockerfile is updated to use new Arcaflow base images where we can centrally control the OS and core dependencies.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2023-07-04 12:10 UTC, dustinblack commented
Testable plugin package built by updated CI: `quay.io/arcalot/arcaflow-plugin-template-python:new-baseimage_3798fde`

2023-07-04 12:21 UTC, dustinblack commented
Dockerfiles for new `osbase` and `buildbase` base images are in this repo:
https://github.com/arcalot/arcaflow-plugin-baseimage-python

Base images are in quay here:
[arcalotarcaflow-plugin-baseimage-python-osbase](https://quay.io/repository/arcalot/arcaflow-plugin-baseimage-python-osbase)
[arcalotarcaflow-plugin-baseimage-python-buildbase](https://quay.io/repository/arcalot/arcaflow-plugin-baseimage-python-buildbase)

Stage 1 of the updated Dockerfile here uses the [buildbase](https://github.com/arcalot/arcaflow-plugin-baseimage-python/blob/main/Dockerfile.buildbase) image, which inherits the core base OS and python install from the [osbase](https://github.com/arcalot/arcaflow-plugin-baseimage-python/blob/main/Dockerfile.osbase) image, installs version-controlled prerequisite python modules, and sets some universal parameters.

Stage 2 of the updated Dockerfile simply uses the [osbase](https://github.com/arcalot/arcaflow-plugin-baseimage-python/blob/main/Dockerfile.osbase) image, standardizing the base OS (currently defined in `osbase` as `centos:stream8`) and python installs.

2023-07-05 13:32 UTC, jdowni000 approved these changes
This is an awesome change that really makes this much cleaner. Well done

2023-07-05 17:53 UTC, mfleader requested changes

2023-07-05 17:54 UTC, mfleader approved these changes

2023-07-05 21:21 UTC, merged